# Generated by Django 4.1.7 on 2023-03-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guests',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
