# Generated by Django 4.1.7 on 2023-03-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='kind',
            field=models.CharField(choices=[('room', 'Room'), ('experiencs', 'Experience')], max_length=15),
        ),
    ]
